version: '3'
services:
  front-end:
    build: ./front-end
    ports:
      - "8080:80"

  back-end-1:
    build: ./back-end

  back-end-2:
    build: ./back-end

  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

